[package]
name = "oxi-tree"
version = "5.3.0"
edition = "2024"
authors = ["TFsadReD"]
license = "Apache-2.0"
description = "A fast and lightweight CLI tool to visualize directory structures"

repository = "https://github.com/TFsadReD/Oxi-Tree"
readme = "README.md"

keywords = ["cli", "tree", "filesystem", "directory-tree"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
colored = "3.1.1"
natord = "1.0.9"
